const express = require("express");
const router  = express.Router();

const data = [
    {
      id: 1,
      title: 'Whispers in the Mist',
      author: 'Eleanor Gray',
      desc: 'A chilling tale set in a small village where ancient secrets emerge with the fog.',
      img: ' i1',
      contentType: ['Horror', 'Fiction'],
      noofviews: 1523,
      nooflikes: 982,
      noofdislikes: 0,
      noofdownloads: 731,
      price: 0,
      publishedDate: '2022-10-18',isUserUploaded: false
    },
    {
      id: 2,
      title: 'Echoes of Tomorrow',
      author: 'Lucas Vane',
      desc: 'A time travel saga that explores a fractured world on the brink of collapse.',
      img: ' i2',
      contentType: ['Sci-Fi', 'Thriller'],
      noofviews: 3472,
      nooflikes: 2001,
      noofdislikes: 35,
      noofdownloads: 1589,
      price: 10,
      publishedDate: '2023-01-15',isUserUploaded: false
    },
    {
      id: 3,
      title: 'Garden of Lies',
      author: 'Sophie Delgado',
      desc: 'A gripping mystery where nothing is as it seems.',
      img: ' i3',
      contentType: ['Mystery', 'Drama', 'Fiction'],
      noofviews: 1893,
      nooflikes: 1103,
      noofdislikes: 12,
      noofdownloads: 921,
      price: 5,
      publishedDate: '2021-08-22',isUserUploaded: false
    },
    {
      id: 4,
      title: 'Crimson Sky',
      author: 'Nolan Pierce',
      desc: 'An epic fantasy where dragons rule the sky and destinies are forged in battle.',
      img: ' i4',
      contentType: ['Fantasy', 'Adventure'],
      noofviews: 4721,
      nooflikes: 3210,
      noofdislikes: 65,
      noofdownloads: 2771,
      price: 12,
      publishedDate: '2022-12-05',isUserUploaded: false
    },
    {
      id: 5,
      title: 'Digital Shadows',
      author: 'Harper Lane',
      desc: 'A cyberpunk thriller that explores identity in a world ruled by data.',
      img: ' i5',
      contentType: ['Cyberpunk', 'Sci-Fi', 'Thriller'],
      noofviews: 2891,
      nooflikes: 1742,
      noofdislikes: 40,
      noofdownloads: 1415,
      price: 8,
      publishedDate: '2024-03-29',isUserUploaded: false
    },
    {
      id: 6,
      title: 'Moonlight Sonata',
      author: 'Clara Ashwin',
      desc: 'A romantic drama that unfolds under the full moon.',
      img: ' i6',
      contentType: ['Romance', 'Drama'],
      noofviews: 1942,
      nooflikes: 1368,
      noofdislikes: 5,
      noofdownloads: 1024,
      price: 0,
      publishedDate: '2023-07-14',isUserUploaded: false
    },
    {
      id: 7,
      title: 'The Forgotten Vault',
      author: 'Darren Cross',
      desc: 'A treasure hunt adventure through ancient ruins.',
      img: ' i7',
      contentType: ['Adventure', 'Mystery', 'Historical'],
      noofviews: 3982,
      nooflikes: 2891,
      noofdislikes: 32,
      noofdownloads: 2110,
      price: 7,
      publishedDate: '2021-11-09',isUserUploaded: false
    },
    {
      id: 8,
      title: 'Steel and Smoke',
      author: 'Jordan Black',
      desc: 'A dystopian rebellion led by a fearless mechanic.',
      img: ' i8',
      contentType: ['Dystopian', 'Action', 'Fiction'],
      noofviews: 3417,
      nooflikes: 2112,
      noofdislikes: 29,
      noofdownloads: 1893,
      price: 9,
      publishedDate: '2022-06-18',isUserUploaded: false
    },
    {
      id: 9,
      title: 'The Last Lighthouse',
      author: 'Erin Hart',
      desc: 'A heartwarming story of solitude, discovery, and resilience.',
      img: ' i9',
      contentType: ['Fiction', 'Slice of Life'],
      noofviews: 1520,
      nooflikes: 1111,
      noofdislikes: 3,
      noofdownloads: 970,
      price: 4,
      publishedDate: '2023-04-02',isUserUploaded: false
    },
    {
      id: 10,
      title: 'Ashes of Eden',
      author: 'Miles Bennett',
      desc: 'An environmental thriller about survival after global collapse.',
      img: ' i10',
      contentType: ['Thriller', 'Sci-Fi', 'Apocalyptic'],
      noofviews: 3294,
      nooflikes: 2124,
      noofdislikes: 41,
      noofdownloads: 1770,
      price: 6,
      publishedDate: '2022-02-20',isUserUploaded: false
    },
    {
      id: 11,
      title: 'Voices Beneath',
      author: 'Talia Moore',
      desc: 'Supernatural events torment a seaside village.',
      img: ' i11',
      contentType: ['Horror', 'Supernatural', 'Mystery'],
      noofviews: 1740,
      nooflikes: 1234,
      noofdislikes: 9,
      noofdownloads: 1022,
      price: 5,
      publishedDate: '2021-10-31',isUserUploaded: false
    },
    {
      id: 12,
      title: 'Code Red',
      author: 'Liam Grant',
      desc: "A tech genius must stop a rogue AI before it's too late.",
      img: ' i12',
      contentType: ['Techno-thriller', 'Sci-Fi', 'Drama'],
      noofviews: 3871,
      nooflikes: 2780,
      noofdislikes: 50,
      noofdownloads: 2403,
      price: 10,
      publishedDate: '2023-09-01',isUserUploaded: false
    },
    {
      id: 13,
      title: 'Painted Truths',
      author: 'Amelia Frost',
      desc: 'A young artist uncovers a conspiracy hidden in plain sight.',
      img: ' i13',
      contentType: ['Fiction', 'Suspense', 'Drama'],
      noofviews: 1843,
      nooflikes: 1321,
      noofdislikes: 6,
      noofdownloads: 1080,
      price: 3,
      publishedDate: '2022-04-10',isUserUploaded: false
    },
    {
      id: 14,
      title: 'The Broken Hourglass',
      author: 'Felix Rowe',
      desc: 'Time manipulation goes wrong in this epic sci-fi saga.',
      img: ' i14',
      contentType: ['Sci-Fi', 'Adventure', 'Fantasy'],
      noofviews: 3221,
      nooflikes: 2044,
      noofdislikes: 19,
      noofdownloads: 1890,
      price: 11,
      publishedDate: '2023-02-11',isUserUploaded: false
    },
    {
      id: 15,
      title: 'Feral',
      author: 'Zoey King',
      desc: 'Wild instincts awaken in a woman trapped in the forest.',
      img: ' i15',
      contentType: ['Thriller', 'Horror', 'Survival'],
      noofviews: 2711,
      nooflikes: 1730,
      noofdislikes: 14,
      noofdownloads: 1499,
      price: 6,
      publishedDate: '2021-05-28',isUserUploaded: false
    },
    {
      id: 16,
      title: 'Neon Rain',
      author: 'Victor Hayes',
      desc: 'A noir detective story set in a neon-lit future.',
      img: ' i16',
      contentType: ['Noir', 'Cyberpunk', 'Mystery'],
      noofviews: 3090,
      nooflikes: 2203,
      noofdislikes: 22,
      noofdownloads: 1901,
      price: 9,
      publishedDate: '2024-01-04',isUserUploaded: false
    },
    {
      id: 17,
      title: 'Shifting Sands',
      author: 'Emily Rose',
      desc: 'A geopolitical drama across deserts of conflict.',
      img: ' i17',
      contentType: ['Drama', 'Historical', 'Political'],
      noofviews: 2010,
      nooflikes: 1500,
      noofdislikes: 8,
      noofdownloads: 1330,
      price: 7,
      publishedDate: '2023-05-18',isUserUploaded: false
    },
    {
      id: 18,
      title: 'Beneath the Marble Sky',
      author: 'Ishaan Patel',
      desc: 'An architectural mystery with ancient roots.',
      img: ' i18',
      contentType: ['Historical', 'Mystery', 'Cultural'],
      noofviews: 1629,
      nooflikes: 1180,
      noofdislikes: 4,
      noofdownloads: 1092,
      price: 4,
      publishedDate: '2022-11-12',isUserUploaded: false
    },
    {
      id: 19,
      title: 'When Crows Sing',
      author: 'Renee Lark',
      desc: 'Dark poetic narrative with elements of folklore.',
      img: ' i19',
      contentType: ['Folklore', 'Horror', 'Fantasy'],
      noofviews: 2455,
      nooflikes: 1777,
      noofdislikes: 11,
      noofdownloads: 1605,
      price: 6,
      publishedDate: '2021-12-24',isUserUploaded: false
    },
    {
      id: 20,
      title: 'The Marble Court',
      author: 'George Quinn',
      desc: 'A legal thriller that challenges the notion of justice.',
      img: ' i20',
      contentType: ['Legal', 'Thriller', 'Drama'],
      noofviews: 2238,
      nooflikes: 1438,
      noofdislikes: 18,
      noofdownloads: 1209,
      price: 5,
      publishedDate: '2023-06-16',isUserUploaded: false
    },
    {
      id: 21,
      title: 'Forgotten Shores',
      author: 'Isla Barrett',
      desc: 'Tales of forgotten lands and lost civilizations.',
      img: ' i21',
      contentType: ['Fantasy', 'Adventure', 'Mythology'],
      noofviews: 2945,
      nooflikes: 2033,
      noofdislikes: 23,
      noofdownloads: 1771,
      price: 10,
      publishedDate: '2022-08-30',isUserUploaded: false
    },
    {
      id: 22,
      title: "The Mind's Labyrinth",
      author: 'Dr. Alan West',
      desc: 'A psychological journey through trauma and memory.',
      img: ' i22',
      contentType: ['Psychological', 'Fiction', 'Suspense'],
      noofviews: 2510,
      nooflikes: 1740,
      noofdislikes: 16,
      noofdownloads: 1485,
      price: 6,
      publishedDate: '2024-05-01',isUserUploaded: false
    },
    {
      id: 23,
      title: 'Mirrors of Illusion',
      author: 'Kayla Hunt',
      desc: 'A magician faces the dark truth behind her powers.',
      img: ' i23',
      contentType: ['Fantasy', 'Mystery', 'Magical Realism'],
      noofviews: 2322,
      nooflikes: 1599,
      noofdislikes: 10,
      noofdownloads: 1362,
      price: 8,
      publishedDate: '2023-10-12',isUserUploaded: false
    },
    {
      id: 24,
      title: "River's Edge",
      author: 'Colin Drake',
      desc: 'Two brothers torn apart by secrets meet again at the river.',
      img: ' i24',
      contentType: ['Drama', 'Family', 'Fiction'],
      noofviews: 1765,
      nooflikes: 1330,
      noofdislikes: 7,
      noofdownloads: 1144,
      price: 3,
      publishedDate: '2021-03-06',isUserUploaded: false
    },
    {
      id: 25,
      title: 'Night Bloom',
      author: 'Mira Celeste',
      desc: 'An enchanted forest where flowers bloom only at midnight.',
      img: ' i25',
      contentType: ['Fantasy', 'Romance', 'Magical Realism'],
      noofviews: 2681,
      nooflikes: 1913,
      noofdislikes: 12,
      noofdownloads: 1675,
      price: 5,
      publishedDate: '2024-09-19',isUserUploaded: false
    }
  ]

router.get("/" , (req,res)=> {
  res.json(data);
})

module.exports = router;
